title: Phạm Tiến Nam's Blog
author: tiennampham23
email: phamtiennam2301@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Angular, Python, C#, Java, JS, Javascript, React, Vue, ReactJs, VueJs, NoSQL, SQL, Spring, ASP.NET
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Pham Tien Nam
  tagline: Full-stack Developer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content

  # generate social links in footer
  social_links:
    twitter: phamtiennam2301
    github:  tiennampham23
    rss: rss
    # dribbble: jekyll
    facebook: phamtiennam23
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md
remote_theme: thelehhman/plainwhite-jekyll
# Build settings
theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed